name: Commitlint

permissions:
  contents: read
  pull-requests: write

on: [pull_request]

jobs:
  lint:
    runs-on: small-runner
    steps:
      - uses: stone-payments/approved-actions/actions/checkout/v4@stable
        with:
          fetch-depth: 0

      - uses: stone-payments/approved-actions/actions/setup-node/v4@stable
        with:
          node-version: 20

      - name: Install commitlint
        run: |
          npm install conventional-changelog-conventionalcommits
          npm install commitlint@latest

      - name: Validate PR commits with commitlint
        run: |
          npx commitlint --from ${{ github.event.pull_request.base.sha }} --to ${{ github.event.pull_request.head.sha }} --verbose
