name: PublishPlugin

on:
  release:
    types: [published]

  workflow_dispatch:

env:
  LUA: "lua=5.1"

jobs:
  publish:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: before install
        run: |
          sudo apt-get update
          sudo apt-get install -y libssl-dev luarocks
          sudo pip install hererocks
          sudo hererocks lua_install -r^ --${{ env.LUA }}
          export PATH=$PATH:$PWD/lua_install/bin

      - name: install
        run: |
          git config --global url.https://github.com/.insteadOf git://github.com/
          sudo make setup
          sudo make install

      - name: deploy
        run: |
          luarocks upload kong-plugin-template-transformer-*.rockspec --api-key=${{ secrets.LUAROCKS_API_KEY }}
